sudo: required
language: csharp
mono: none

install:
- docker build -t docker-gc-test -f Dockerfile.test .
- docker build -t docker-gc-helm-chart-validate -f Dockerfile.helmtest .

script:
- docker build -t src/docker-cache-cleaner -f Dockerfile .

after_success:
- docker build -t src/docker-cache-cleaner -f Dockerfile .
