# DockerGC Unit Tests Dockerfile

FROM mcr.microsoft.com/dotnet/sdk:5.0

COPY DockerGC DockerGC
COPY DockerGC.Tests DockerGC.Tests
WORKDIR /DockerGC.Tests

RUN ["dotnet", "restore"]
RUN ["dotnet", "test"]

ENTRYPOINT ["dotnet", "run"]