# Default values for docker-gc.
image:
  # repository: jackil/docker-gc
  #Repository should be moved to AIR Shared Container Registry
  #repository: airsharedcontainers.azurecr.io/docker-gc
  repository: viennadroptest.azurecr.io/docker-cache-cleaner
  tag: latest
  pullPolicy: IfNotPresent
  # optional pull secrets
  # pullSecrets: 
  # - "airsharedcontainers"
docker:
  socketPath: /var/run/docker.sock
  volumeName: docker-volume
fullnameOverride: docker-cache-cleaner
nameOverride: docker-cache-cleaner
statsd:
  enabled: false
  #host: localhost
  #port: 8125
config:
  dockerEndpoint: unix:///var/run/docker.sock
  executionIntervalInMinutes: 60
  dockerClientTimeoutInSeconds: 180
  imageDeletionOrder: ByImageLastTouchDate
  #imageDeletionOrder: ByImageCreationDate
  strategy: ByDate
  daysBeforeDeletion: 30
  #strategy: ByDiskSpace
  #sizeLimitInGigabyte:
  containerStateBlacklist: dead,exited
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: "0"
    memory: 128Mi

